# Generated by Django 5.2 on 2025-05-09 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenitsu_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='zenitsu_shop.deliverymethod', verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='zenitsu_shop.paymentmethod', verbose_name='Способ оплаты'),
        ),
    ]
