# Generated by Django 5.2 on 2025-05-12 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenitsu_shop', '0004_order_yookassa_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zenitsu_shop.size'),
        ),
    ]
