# Generated by Django 5.2 on 2025-05-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zenitsu_shop', '0006_orderitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
