# Generated by Django 5.2 on 2025-05-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zenitsu_shop', '0007_remove_orderitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='yookassa_payment_id',
        ),
    ]
