# Generated by Django 5.2 on 2025-05-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zenitsu_shop', '0009_order_yookassa_payment_id_orderitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
