# Generated by Django 5.2 on 2025-05-12 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenitsu_shop', '0012_remove_cartitem_size_remove_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Итоговая стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zenitsu_shop.deliverymethod', verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zenitsu_shop.paymentmethod', verbose_name='Способ оплаты'),
        ),
    ]
